<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\PhotoShelf.Application\PhotoShelf.Application.csproj" />
    <ProjectReference Include="..\PhotoShelf.Domain\PhotoShelf.Domain.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.8" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\*.sql" />
  </ItemGroup>
</Project>

